quotes_to_scrape/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("tag/", views.tag, name="tag"),
    path("quote/", views.quote, name="quote"),
    path("author/", views.author, name="author"),
    path("about/<author_id>", views.about, name="about"),
    path("<int:page>", views.main, name="root_paginate"),
]

quotes_to_scrape/quotes_to_scrape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

quotes_to_scrape/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
]

quotes_to_scrape/quotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "name"], name="tag of username")
        ]

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"

quotes_to_scrape/users/models.py
from django.db import models

# Create your models here.

quotes_to_scrape/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote, Tag


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all(), widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote','author']
        exclude = ['tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput)
    born_date = CharField(max_length=50, required=True, widget=TextInput)
    born_location = CharField(max_length=150, required=True, widget=TextInput)
    description = CharField(max_length=4000,required=True, widget=TextInput)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes_to_scrape/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    password1 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

quotes_to_scrape/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator

from .forms import QuoteForm, AuthorForm, TagForm
from .models import Author, Tag
from utils.mongo_migration import Quote as QuoteMongo


# Create your views here.
def main(request, page=1):
    quotes = QuoteMongo.objects()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


@login_required
def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/tag.html", {"form": form})

    return render(request, "quotes/tag.html", {"form": TagForm()})


@login_required
def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "quotes/author.html", {"form": form})

    return render(request, "quotes/author.html", {"form": AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quotes:root")
        else:
            return render(
                request,
                "quotes/quote.html",
                {"tags": tags, "form": form},
            )

    return render(
        request,
        "quotes/quote.html",
        {"tags": tags, "form": QuoteForm()},
    )


def about(request, author_id):
    author = get_object_or_404(Author, pk=author_id)

    return render(request, "quotes/about.html", {"author": author})

quotes_to_scrape/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:root")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:root")
        else:
            return render(request, "users/signup.html", context={"form": form})

    return render(request, "users/signup.html", context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:root")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="quotes:root")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to="quotes:root")

quotes_to_scrape/quotes/templates/quotes/about.html
{% extends "quotes/base.html" %} {% block content %}

<div class="container-fluid">
  <p>
    <strong>{{ author.fullname }}</strong>
  </p>
  <p>Born date: {{ author.born_date }}</p>
  <p>Born in: {{ author.born_location }}</p>
  <p>Description: {{ author.description }}</p>
</div>

{% endblock %}

quotes_to_scrape/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %} {% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label>Author fullname: {{form.fullname}} </label>
    <span>{{ form.errors.fullname }}</span>
    <label>Author born date: {{form.born_date}} </label>
    <span>{{ form.errors.born_date }}</span>
    <label>Author born location: {{form.born_location}} </label>
    <span>{{ form.errors.born_location }}</span>
    <label>Author description: {{form.description}} </label>
    <span>{{ form.errors.description }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

quotes_to_scrape/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}" />
    <title>Quotes</title>
  </head>
  <body>
    <div class="container">
      <div class="row header-box pt-3 bm-3">
        <div class="col-md-8">
          <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
          </h1>
        </div>
        <div class="col-md-4">
          {% if user.is_authenticated %}
          <p>
            <h2> Welcome <b>{{ user.username }}!</b></h2>
            <a href="{% url 'quotes:quote' %}" class="btn btn-primary"
              >Add Quote</a
            >
            <a href="{% url 'quotes:author' %}" class="btn btn-primary"
              >Add Author</a
            >
            <a href="{% url 'quotes:tag' %}" class="btn btn-primary">Add Tag</a>
            <a href="{% url 'users:logout' %}" class="btn btn-primary"
              >Logout</a
            >
          </p>
          {% else %}
          <p>
            <a href="{% url 'users:signup' %}" class="btn btn-primary"
              >SignUp</a
            >
            <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
          </p>
          {% endif %}
        </div>
      </div>

      {% block content %} {% endblock %}
    </div>
  </body>
</html>

quotes_to_scrape/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{quote.quote}} </span>
      <span
        >by
        <small class="author" itemprop="author"
          >{{quote.author.fullname}}</small
        >
        <a href="/about/{{quote.author}}">(about)</a>
      </span>
      <div class="tags">
        Tags: {% for tag in quote.tags %}
        <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <nav>
      <ul class="pager">
        <li class="previous">
          <a
            class="{% if not quotes.has_previous%} disabled {% endif %}"
            href="{% if quotes.has_previous%} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"
          >
            <span aria-hidden="true">←</span> Previous
          </a>
        </li>

        <li class="next">
          <a
            class="{% if not quotes.has_next%} disabled {% endif %}"
            href="{% if quotes.has_next%} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}"
          >
            Next <span aria-hidden="true">→</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

{% endblock %}

quotes_to_scrape/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %} {% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Enter the quote: {{form.quote}} </label>
    <span>{{form.error.quote}}</span>
  </div>
  <div style="padding: 10px"></div>
    <label> Enter the author: {{form.author}} </label>
    <span>{{form.error.author}}</span>
  </div>
  <div style="padding: 10px"></div>
    <label>
      Select tags:
      <select name="tags" multiple="multiple" required>
        {% for tag in tags %}
        <option value="{{tag.name}}">{{tag.name}}</option>
        {% endfor %}
      </select>
    </label>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

quotes_to_scrape/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %} {% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label>Enter the tag name: {{form.name}} </label>
    <span>{{ form.errors.name }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

quotes_to_scrape/users/templates/users/login.html
{% extends "quotes/base.html" %} {% block content %} {% if messages %}
<div>
  {% for message in messages %}
  <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
  {% csrf_token %}
  <div>
    <label> Username: {{ form.username }} </label>
  </div>

  <div>
    <label>Password: {{ form.password }} </label>
  </div>

  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

quotes_to_scrape/users/templates/users/signup.html
{% extends "quotes/base.html" %} {% block content %}

<div>
  <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %}
  <div>
    <label> Username: {{ form.username }} </label>
    <span>{{ form.errors.username }}</span>
  </div>
  <br />
  <div>
    <label> Password: {{ form.password1 }} </label>
    <span>{{ form.errors.password1 }}</span>
  </div>
  <div>
    <label> Password confirmation: {{ form.password2 }} </label>
    <span>{{ form.errors.password2 }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}